UserDetails/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace UserDetails.Models
{
    public class User
    {
        [DisplayName("")]
        public int? Id { get; set; }

        [Required]
        [DisplayName("User name")]
        public string UserName { get; set; }

        [DisplayName("Password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [DisplayName("Firstname")]
        public string FirstName { get; set; }

        [Required]
        [DisplayName("Surname")]
        public string SurName { get; set; }

        [Required]
        [RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$")]
        [DisplayName("E-mail")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DisplayName("Phone number")]
        [DataType(DataType.PhoneNumber)]
        public string Phone { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayName("Birth date")]
        public DateTime? BirthDate { get; set; }

        [Required]
        [DisplayName("Birth place")]
        public string BirthPlace { get; set; }
    }
}

UserDetails/ViewModels/DetailsViewModel.cs
using UserDetails.Models;
using UserDetails.Validations;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace UserDetails.ViewModels
{
    public class DetailsViewModel
    {
        private User _user;
        public User User
        {
            get
            {
                return _user;
            }
            set
            {
                _user = value;

                if (User != null && User.Id != null)
                {
                    Title = User.UserName + " details";
                    Exist = true;
                }
                else Title = "Add a new user";
            }
        }

        public string Title { get; set; }

        public bool Exist { get; set; }

        public string Password { get; set; }

        [DisplayName("Current password")]
        [DataType(DataType.Password)]
        [RequiredIf(nameof(Exist), true)]
        public string CurrentPassword { get; set; }

        [DisplayName("New password")]
        [DataType(DataType.Password)]
        [RequiredIf(nameof(Exist), false)]
        public string NewPassword { get; set; }

        [DisplayName("Confirm password")]
        [DataType(DataType.Password)]
        [Compare("NewPassword")]
        public string PasswordCheck { get; set; }

        public DetailsViewModel() : this(null)
        {

        }

        public DetailsViewModel(User user)
        {
            User = user == null ? new User() : user;
        }
    }
}

UserDetails/ViewModels/ListViewModel.cs
using UserDetails.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UserDetails.ViewModels
{
    public class ListViewModel
    {
        public List<User> UserList { get; set; }
    }
}

UserDetails/ViewModels/LoginViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace UserDetails.ViewModels
{
    public class LoginViewModel
    {
        [BindProperty]
        [Required, StringLength(100, MinimumLength = 3)]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [BindProperty]
        [Required, StringLength(100, MinimumLength = 3)]
        [Display(Name = "Password")]
        public string Password { get; set; }
    }
}

UserDetails/Controllers/DetailsController.cs
using UserDetails.Interfaces;
using UserDetails.Models;
using UserDetails.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace UserDetails.Controllers
{
    [Route("")]
    public class DetailsController : Controller
    {
        private IUserRepository _usersRepository;

        private DetailsViewModel _dvm;

        public DetailsController(IUserRepository usersRepository)
        {
            _usersRepository = usersRepository;
        }

        [Route("Add")]
        public IActionResult Details()
        {
            _dvm = new DetailsViewModel();
            return View(_dvm);
        }

        [HttpPost("Add")]
        public IActionResult Save(DetailsViewModel vm)
        {
            bool accept;

            if (vm.User.Id != null)
            {
                accept = vm.CurrentPassword == _usersRepository.GetSingleById((int)vm.User.Id).Password;
                vm.User.Password = vm.CurrentPassword;
            }
            else accept = true;

            if (ModelState.IsValid && accept)
            {
                if (!string.IsNullOrEmpty(vm.PasswordCheck))
                    vm.User.Password = vm.PasswordCheck;

                if (vm.User.Id != null)
                    _usersRepository.UdateSingle(vm.User);
                else
                    _usersRepository.AddSingle(vm.User);

                return RedirectToAction(nameof(ListController.List), "List");
            }
            return View(nameof(Details), vm);
        }

        [Route("Edit/{user}")]
        public IActionResult Edit(int user)
        {
            _dvm = new DetailsViewModel(_usersRepository.GetSingleById(user));
            return View(nameof(Details), _dvm);
        }
    }
}

UserDetails/Controllers/ListController.cs
using UserDetails.Interfaces;
using UserDetails.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UserDetails.Controllers
{
    [Route("")]
    public class ListController : Controller
    {
        private IUserRepository _usersRepository;

        public ListController(IUserRepository usersRepository)
        {
            _usersRepository = usersRepository;
        }

        [Route("List")]
        public IActionResult List()
        {
            ListViewModel lvm = new ListViewModel();
            lvm.UserList = _usersRepository.GetAll().ToList();
            return View(lvm);
        }

        [Route("Delete/{user}")]
        public IActionResult Delete(int user)
        {
            _usersRepository.Remove(user);
            return RedirectToAction(nameof(List));
        }
    }
}

UserDetails/Controllers/LoginController.cs
using UserDetails.Interfaces;
using UserDetails.Models;
using UserDetails.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace UserDetails.Controllers
{
    [Route("")]
    public class LoginController : Controller
    {
        private IUserRepository _usersRepository;

        public LoginController(IUserRepository usersRepository)
        {
            _usersRepository = usersRepository;
        }

        [Route("")]
        public IActionResult Index()
        {
            LoginViewModel _loginVM = new LoginViewModel();
            return View(_loginVM);
        }

        [HttpPost("")]
        public IActionResult Login(LoginViewModel vm)
        {
            if (ModelState.IsValid)
            {
                User user = _usersRepository.GetSingleByUserName(vm.UserName);

                if (user.Password == vm.Password)
                    return RedirectToAction(nameof(ListController.List), "List");

                else return View(nameof(Index), vm);
            }
            return View(nameof(Index), vm);
        }
    }
}

UserDetails/Views/Details/Details.cshtml
@model UserDetails.ViewModels.DetailsViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <title></title>
</head>

<body>
    <h1>
        @Model.Title
    </h1>
    <form asp-action="Save" method="post">
        @Html.HiddenFor(model => model.User.Id)
        <table class="table">
            <tr>
                <th>
                    <label asp-for="User.UserName"></label>
                </th>
                <td>
                    <input asp-for="User.UserName" />
                </td>
                <td>
                    <span asp-validation-for="User.UserName"></span>
                </td>
            </tr>
            <tr>
                <th>
                    <label asp-for="User.FirstName"></label>
                </th>
                <td>
                    <input asp-for="User.FirstName">
                </td>
                <td>
                    <span asp-validation-for="User.FirstName"></span>
                </td>
            </tr>
            <tr>
                <th>
                    <label asp-for="User.SurName"></label>
                </th>
                <td>
                    <input asp-for="User.SurName">
                </td>
                <td>
                    <span asp-validation-for="User.SurName"></span>
                </td>
            </tr>
            <tr>
                <th>
                    <label asp-for="User.Email"></label>
                </th>
                <td>
                    <input asp-for="User.Email">
                </td>
                <td>
                    <span asp-validation-for="User.Email"></span>
                </td>
            </tr>
            <tr>
                <th>
                    <label asp-for="User.Phone"></label>
                </th>
                <td>
                    <input asp-for="User.Phone">
                </td>
                <td>
                    <span asp-validation-for="User.Phone"></span>
                </td>
            </tr>
            <tr>
                <th>
                    <label asp-for="User.BirthDate"></label>
                </th>
                <td>
                    <input asp-for="User.BirthDate">
                </td>
                <td>
                    <span asp-validation-for="User.BirthDate"></span>
                </td>
            </tr>
            <tr>
                <th>
                    <label asp-for="User.BirthPlace"></label>
                </th>
                <td>
                    <input asp-for="User.BirthPlace">
                </td>
                <td>
                    <span asp-validation-for="User.BirthPlace"></span>
                </td>
            </tr>
            <tr>
                <th>
                    <label asp-for="CurrentPassword"></label>
                </th>
                <td>
                    <input type="password" asp-for="CurrentPassword" disabled="@(!Model.Exist)">
                </td>
                <td>
                    <span asp-validation-for="CurrentPassword"></span>
                </td>
            </tr>
            <tr>
                <th>
                    <label asp-for="NewPassword"></label>
                </th>
                <td>
                    <input type="password" asp-for="NewPassword">
                </td>
                <td>
                    <span asp-validation-for="NewPassword"></span>
                </td>
            </tr>
            <tr>
                <th>
                    <label asp-for="PasswordCheck"></label>
                </th>
                <td>
                    <input type="password" asp-for="PasswordCheck">
                </td>
                <td>
                    <span asp-validation-for="PasswordCheck"></span>
                </td>
            </tr>
            <tr>
                <td>
                    <button type="submit">Save</button>
                </td>
                <td>
                    <a asp-Controller="List" asp-action="List">Back</a>
                </td>
            </tr>
        </table>
    </form>
</body>
</html>

UserDetails/Views/List/List.cshtml
@model UserDetails.ViewModels.ListViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <title></title>
</head>

<body>
    <h1>List of users</h1>

    <a asp-controller="Details" asp-action="Details">Add new user</a>
    <br />
    <input type="text" id="searchField" onkeyup="searchFunction()" placeholder="Search...">

    <table class="table" id="usersTable">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.UserList[0].Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserList[0].FirstName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserList[0].SurName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserList[0].UserName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserList[0].Email)
                </th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.UserList)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SurName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        <a asp-controller="Details" asp-action="Edit" asp-route-user="@item.Id">Edit</a>
                    </td>
                    <td>
                        <a asp-action="Delete" asp-route-user="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <script>
        function searchFunction() {
            var input = document.getElementById("searchField");
            var filter = input.value.toUpperCase();
            var table = document.getElementById("usersTable");
            var trs = table.tBodies[0].getElementsByTagName("tr");

            for (var i = 0; i < trs.length; i++) {
                var tds = trs[i].getElementsByTagName("td");
                trs[i].style.display = "none";

                for (var i2 = 0; i2 < tds.length; i2++) {
                    if (tds[i2].innerHTML.toUpperCase().indexOf(filter) > -1) {
                        trs[i].style.display = "";
                        continue;
                    }
                }
            }
        }
    </script>
</body>
</html>

UserDetails/Views/Login/Index.cshtml
@model UserDetails.ViewModels.LoginViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <title></title>
</head>

<body>
    <h1>Login</h1>
    <form asp-action="Login" method="post">
        <table class="table">
            <tr>
                <td>
                    <label asp-for="UserName"></label>
                </td>
                <td>
                    <input asp-for="UserName" />
                </td>
                <td>
                    <span asp-validation-for="UserName"></span>
                </td>
            </tr>
            <tr>
                <td>
                    <label asp-for="Password"></label>
                </td>
                <td>
                    <input type="password" asp-for="Password" />
                </td>
                <td>
                    <span asp-validation-for="Password"></span>
                </td>
            </tr>
            <tr>
                <td>
                    <button type="submit">Login</button>
                </td>
            </tr>
        </table>
    </form>
</body>
</html>

UserDetails/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css" />

</head>
<body>
    <div>
        @RenderBody()
    </div>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"></script>
</body>
</html>